project_id = "bpxusdvpzqdtttfmbyai"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
anonymous_key_enabled = false

[functions.clone-repository]
verify_jwt = true

[functions.github-webhook]
verify_jwt = false

[functions.setup-webhook]
verify_jwt = true

[functions.sync-repository]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15