// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpxusdvpzqdtttfmbyai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJweHVzZHZwenFkdHR0Zm1ieWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTM0NTAsImV4cCI6MjA2ODEyOTQ1MH0.X7ycYcF3evEtYiZKlgmzXax8BFEksSLf0Fti6XQ4-Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});